### ISSUE TITLE
Exception thrown in SettingsProviderComponent.getOutPairs() when starting PHPStorm after plugin installation

### ISSUE THREAD

**Issue by robations** [editorconfig/editorconfig-jetbrains#18]
As well as the exception, noticed some unexpected side-effects as well:
- 'show whitespace' editor appearance option disabled on application start
- clicking beyond end of line inserts cursor at that position instead of at end of line

Disabling the editorconfig plugin and restarting fixes the above issues.

OS X 10.8.4 / JRE 1.6.0_51 / PHPStorm 6.0.3

Stack trace given as:

```
[Ljava.lang.StackTraceElement;@a99e6a
java.lang.Throwable
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:54)
at com.intellij.openapi.diagnostic.Logger.error(Logger.java:57)
at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:90)
at
org.editorconfig.plugincomponents.SettingsProviderComponent.getOutPairs(SettingsProviderComponent.java:41)
at     org.editorconfig.configmanagement.EndOfLineManager.applySettings(EndOfLineManager.java:101)
at     org.editorconfig.configmanagement.EndOfLineManager.doneSavingAllDocuments(EndOfLineManager.java:86)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at     sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at      sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at     com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:120)
at     com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
at     com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:234)
at     com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
at     com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
at     com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
at     com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
at com.sun.proxy.$Proxy36.doneSavingAllDocuments(Unknown Source)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at     sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
at     sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
at java.lang.reflect.Method.invoke(Method.java:597)
at     org.editorconfig.plugincomponents.ReplacementFileDocumentManager.multiCast(ReplacementFileDocumentManager.java:46)
at     org.editorconfig.plugincomponents.ReplacementFileDocumentManager.access$000(ReplacementFileDocumentManager.java:19)
at     org.editorconfig.plugincomponents.ReplacementFileDocumentManager$1.invoke(ReplacementFileDocumentManager.java:34)
at com.sun.proxy.$Proxy36.doneSavingAllDocuments(Unknown Source)
at     org.editorconfig.plugincomponents.ReplacementFileDocumentManager.saveAllDocuments(ReplacementFileDocumentManager.java:62)
at     com.intellij.ide.SaveAndSyncHandlerImpl.saveProjectsAndDocuments(SaveAndSyncHandlerImpl.java:139)
at     com.intellij.ide.SaveAndSyncHandlerImpl$3.onFrameDeactivated(SaveAndSyncHandlerImpl.java:100)
at com.intellij.ide.FrameStateManagerImpl.a(FrameStateManagerImpl.java:100)
at     com.intellij.ide.FrameStateManagerImpl.access$500(FrameStateManagerImpl.java:34)
at     com.intellij.ide.FrameStateManagerImpl$2$1.run(FrameStateManagerImpl.java:73)
at com.intellij.util.Alarm$Request$1.run(Alarm.java:289)
at     com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:343)
at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
at java.awt.EventQueue.access$400(EventQueue.java:82)
at java.awt.EventQueue$2.run(EventQueue.java:676)
at java.awt.EventQueue$2.run(EventQueue.java:674)
at java.security.AccessController.doPrivileged(Native Method)
at     java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
at     java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
at     java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
at     java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by robations** [comment]
On second reading, sounds related to #14.

**Comment by bellkev** [comment]
This must be resolved now, as EndOfLineManager is gone in the current version.
