### ISSUE TITLE
Must not modify PSI inside save listener

### ISSUE THREAD

**Issue by hippee-lee** [editorconfig/editorconfig-jetbrains#46]
WebStorm keeps throwing the following error and this is the Error message: 
- Must not modify PSI inside save listener: Must not modify PSI inside save listener

Clearing the error doesn't seem to help. 

Here is the stack trace in case you need it:

Must not modify PSI inside save listener: Must not modify PSI inside save listener
com.intellij.util.IncorrectOperationException: Must not modify PSI inside save listener
    at com.intellij.pom.core.impl.PomModelImpl.runTransaction(PomModelImpl.java:139)
    at com.intellij.psi.impl.DocumentCommitProcessor.doActualPsiChange(DocumentCommitProcessor.java:174)
    at com.intellij.psi.impl.DocumentCommitProcessor$1$1.run(DocumentCommitProcessor.java:142)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$8.compute(CodeStyleManagerImpl.java:669)
    at com.intellij.psi.impl.source.PostprocessReformattingAspect.disablePostprocessFormattingInside(PostprocessReformattingAspect.java:116)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl$10.compute(CodeStyleManagerImpl.java:704)
    at com.intellij.formatting.FormatterImpl.runWithFormattingDisabled(FormatterImpl.java:812)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:700)
    at com.intellij.psi.impl.source.codeStyle.CodeStyleManagerImpl.performActionWithFormatterDisabled(CodeStyleManagerImpl.java:666)
    at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:138)
    at com.intellij.psi.impl.DocumentCommitProcessor$1.process(DocumentCommitProcessor.java:128)
    at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommitInWriteAction(PsiDocumentManagerBase.java:323)
    at com.intellij.psi.impl.PsiDocumentManagerImpl.finishCommitInWriteAction(PsiDocumentManagerImpl.java:141)
    at com.intellij.psi.impl.PsiDocumentManagerBase$2.run(PsiDocumentManagerBase.java:291)
    at com.intellij.openapi.application.impl.ApplicationImpl.runWriteAction(ApplicationImpl.java:984)
    at com.intellij.psi.impl.PsiDocumentManagerBase.finishCommit(PsiDocumentManagerBase.java:288)
    at com.intellij.psi.impl.DocumentCommitThread$4.run(DocumentCommitThread.java:477)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at com.intellij.ide.IdeEventQueue.pumpEventsForHierarchy(IdeEventQueue.java:767)
    at com.intellij.openapi.progress.util.ProgressWindow.startBlocking(ProgressWindow.java:199)
    at com.intellij.openapi.application.impl.ApplicationImpl.runProcessWithProgressSynchronously(ApplicationImpl.java:665)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.a(ProgressManagerImpl.java:277)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:272)
    at com.intellij.openapi.progress.impl.ProgressManagerImpl.runProcessWithProgressSynchronously(ProgressManagerImpl.java:225)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.a(EncodingProjectManagerImpl.java:417)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.c(EncodingProjectManagerImpl.java:426)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.setEncoding(EncodingProjectManagerImpl.java:228)
    at org.editorconfig.configmanagement.EncodingManager.applySettings(EncodingManager.java:63)
    at org.editorconfig.configmanagement.EncodingManager.beforeDocumentSaving(EncodingManager.java:49)
    at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:234)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:207)
    at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
    at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
    at com.sun.proxy.$Proxy17.beforeAllDocumentsSaving(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:127)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:87)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:115)
    at com.sun.proxy.$Proxy17.beforeAllDocumentsSaving(Unknown Source)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:307)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:298)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.a(EncodingProjectManagerImpl.java:416)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.c(EncodingProjectManagerImpl.java:426)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.setEncoding(EncodingProjectManagerImpl.java:228)
    at org.editorconfig.configmanagement.EncodingManager.applySettings(EncodingManager.java:63)
    at org.editorconfig.configmanagement.EncodingManager.beforeDocumentSaving(EncodingManager.java:49)
    at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:234)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:207)
    at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
    at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
    at com.sun.proxy.$Proxy17.beforeAllDocumentsSaving(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor73.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:127)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:87)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:115)
    at com.sun.proxy.$Proxy17.beforeAllDocumentsSaving(Unknown Source)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:307)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveAllDocuments(FileDocumentManagerImpl.java:298)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.a(EncodingProjectManagerImpl.java:416)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.c(EncodingProjectManagerImpl.java:426)
    at com.intellij.openapi.vfs.encoding.EncodingProjectManagerImpl.setEncoding(EncodingProjectManagerImpl.java:228)
    at org.editorconfig.configmanagement.EncodingManager.applySettings(EncodingManager.java:63)
    at org.editorconfig.configmanagement.EncodingManager.beforeDocumentSaving(EncodingManager.java:49)
    at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.util.messages.impl.MessageBusConnectionImpl.deliverMessage(MessageBusConnectionImpl.java:114)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:228)
    at com.intellij.util.messages.impl.MessageBusImpl.doPumpMessages(MessageBusImpl.java:234)
    at com.intellij.util.messages.impl.MessageBusImpl.pumpMessages(MessageBusImpl.java:219)
    at com.intellij.util.messages.impl.MessageBusImpl.sendMessage(MessageBusImpl.java:209)
    at com.intellij.util.messages.impl.MessageBusImpl.access$000(MessageBusImpl.java:43)
    at com.intellij.util.messages.impl.MessageBusImpl$1.invoke(MessageBusImpl.java:131)
    at com.sun.proxy.$Proxy17.beforeDocumentSaving(Unknown Source)
    at sun.reflect.GeneratedMethodAccessor351.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:127)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.access$000(FileDocumentManagerImpl.java:87)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$1.invoke(FileDocumentManagerImpl.java:115)
    at com.sun.proxy.$Proxy17.beforeDocumentSaving(Unknown Source)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl$5.run(FileDocumentManagerImpl.java:427)
    at com.intellij.pom.core.impl.PomModelImpl.guardPsiModificationsIn(PomModelImpl.java:340)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:424)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.a(FileDocumentManagerImpl.java:398)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:349)
    at com.intellij.openapi.fileEditor.impl.FileDocumentManagerImpl.saveDocument(FileDocumentManagerImpl.java:341)
    at com.intellij.openapi.vcs.ex.LineStatusTracker$MyDocumentListener$1.run(LineStatusTracker.java:400)
    at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
    at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
    at java.awt.EventQueue.access$400(EventQueue.java:97)
    at java.awt.EventQueue$3.run(EventQueue.java:697)
    at java.awt.EventQueue$3.run(EventQueue.java:691)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
    at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
    at com.intellij.ide.IdeEventQueue.e(IdeEventQueue.java:697)
    at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:524)
    at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:335)
    at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
    at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
    at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
    at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
    at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by denofevil** [comment]
What plugin version are you using?

**Comment by hippee-lee** [comment]
0.4.0

**Comment by boneskull** [comment]
:+1:

**Comment by hippee-lee** [comment]
@denofevil 0.4.0, my co-worker also experiences the same behavior with same version.

**Comment by denofevil** [comment]
As EditorConfig support is becoming native in all IntelliJ products, I've moved this report to: https://youtrack.jetbrains.com/issue/IDEA-130020, feel free to vote for that issue.

**Comment by hippee-lee** [comment]
There wasn't an obvious way to up vote the issue on your link. 

Is this plug-in going away then? Will it be supported until JetBrains is able to integrate it into WebStorm?

**Comment by denofevil** [comment]
There's :+1: like sign at the bottom of the issue summary.

Yes, this plugin is going away and is already merged into IntelliJ community repository: https://github.com/JetBrains/intellij-community/tree/master/plugins/editorconfig. All the fixes and new features are available in the latest WebStorm EAP or will be in upcoming ones.

**Comment by hippee-lee** [comment]
Thanks for the quick response. The thumbs up button is greyed out and not clickable. Should I uninstall this one and reinstall with the plugin manager?

**Comment by denofevil** [comment]
Are you logged in? It should highlight on hover

**Comment by hippee-lee** [comment]
Sorry, I am unwilling to create an account just to vote. Never mind the vote questions.

**Should I uninstall this one and reinstall with the plugin manager?** Or, What is the best transition from this plugin to the one supported by JetBrains?

**Comment by denofevil** [comment]
EAP build contains EditorConfig plugin with higher version than one from plugin repository, so it should work automatically
